version: '3'

services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  web:
    depends_on:
      - 'redis'
    build:
      context: .
      dockerfile: Dockerfile.compose
    command: bundle exec rails server

    ports:
      - '3036:3036'
    volumes:
      - '.:/app'
    environment:
      - PORT=3036
      - HOST=0.0.0.0
      - REDIS_URL=redis://redis:6379/0

volumes:
  redis:
