version: '3'

services:
  redis:
    image: 'docker.io/library/redis:latest'

  web:
    depends_on:
      - 'redis'
    build:
      context: .
      dockerfile: Dockerfile.compose
    ports:
      - '3036:3036'
    volumes:
      - '.:/app'
    environment:
      - PORT=3036
      - HOST=0.0.0.0
      - REDIS_URL=redis://redis:6379/0
