version: "3"

services:
  redis:
    image: redis
    volumes:
      - ./tmp/redis:/var/lib/redis
  web:
    env_file: .env
    environment:
      REDIS_URL: redis://redis:6379/0
      REDIS_NAMESPACE:
    build: .
    volumes:
      - .:/www
    depends_on:
      - redis
    ports:
      - "3222:3222"
