development:
  adapter: redis
  url: redis://localhost:6379/0

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/0

staging:
  adapter: redis
  url: redis://localhost:6379/0
