development:
  ns: omgdots
  url: redis://localhost:6379/0

test:
  ns: omgdots_test
  url: redis://localhost:6379/0

production:
  ns: omgdots
  url: redis://localhost:6379/0

staging:
  ns: omgdots
  url: redis://localhost:6379/0
